# Generated by Django 5.1.2 on 2025-04-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_color',
            field=models.CharField(default='#3498db', max_length=20),
        ),
    ]
