# Generated by Django 5.1.2 on 2025-04-14 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_background_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visit',
            name='visited',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visits_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='visit',
            name='ip_address',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
