# Generated by Django 5.1.2 on 2025-04-16 10:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_visit_visited_alter_visit_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Краткое описание продукции', null=True)),
                ('category', models.CharField(blank=True, help_text='Категория продукта', max_length=100, null=True)),
                ('keywords', models.CharField(blank=True, help_text='Ключевые слова, разделённые запятыми', max_length=200, null=True)),
                ('encrypted_content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quality', models.PositiveSmallIntegerField(blank=True, help_text='Качество (0-100)', null=True)),
                ('uniqueness', models.PositiveSmallIntegerField(blank=True, help_text='Уникальность (0-100)', null=True)),
                ('spelling', models.PositiveSmallIntegerField(blank=True, help_text='Правописание (0-100)', null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextProductRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Оценка от 1 до 5')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='users.textproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('product', 'user')},
            },
        ),
    ]
