# Generated by Django 5.1.2 on 2025-05-07 21:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0011_textproduct_textproductrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='image',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='status',
        ),
        migrations.AddField(
            model_name='artwork',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='category',
            field=models.CharField(choices=[('cg', 'Компьютерная графика'), ('painting', 'Живопись'), ('drawing', 'Рисунок'), ('photo', 'Фотография'), ('digital', 'Цифровая иллюстрация')], default='cg', max_length=20, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='censored_areas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='original_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/originals/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/previews/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ArtworkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artworks/series/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Порядок на странице')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='users.artwork')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('artwork', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ArtworkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'artwork')},
            },
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USDT', 'Tether USD'), ('OSP', 'Ospyral Coin')], max_length=4)),
                ('address', models.CharField(max_length=128, unique=True)),
                ('balance', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='CryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('deposit', 'Deposit'), ('escrow', 'Escrow'), ('release', 'Release'), ('purchase', 'Purchase')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('tx_hash', models.CharField(blank=True, max_length=66)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='txs', to='users.cryptowallet')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=36)),
                ('message', models.TextField(blank=True, help_text='Ваше сообщение-поздравление')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TextProductOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.textproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'product')},
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
