# Generated by Django 5.1.2 on 2025-05-22 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_product_owner_remove_artwork_current_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textproduct',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Tether USD'), ('OSP', 'Ospyral Coin')], default='USDT', max_length=4),
        ),
        migrations.AddField(
            model_name='textproduct',
            name='pages',
            field=models.PositiveSmallIntegerField(default=1, help_text='Количество страниц (1–100)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textproduct',
            name='category',
            field=models.CharField(blank=True, choices=[], help_text='Категория продукта', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='textproduct',
            name='keywords',
            field=models.CharField(blank=True, help_text='Теги через #, не больше 10', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='textproduct',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
