# Generated by Django 5.1.2 on 2025-05-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_textproduct_currency_textproduct_pages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Аналитика и Исследования', [('geopolitika', 'Геополитика'), ('economika_finansy', 'Экономика и финансы'), ('socialnye_processy', 'Социальные процессы'), ('nauchnye_obzory', 'Научные обзоры')]), ('Психология и Человеческое поведение', [('poved_psikhologiya', 'Поведенческая психология'), ('temnaya_psikhologiya', 'Темная психология'), ('emoc_intellekt', 'Эмоциональный интеллект'), ('samoanaliz_samokontrol', 'Самоанализ и самоконтроль')]), ('Философия и Мировоззрение', [('etika_i_moral', 'Этика и мораль'), ('logika_i_ratsionalnost', 'Логика и рациональность'), ('ontologiya_myshlenie', 'Онтология, мышление'), ('sovremennaya_filosofiya', 'Современная философия')]), ('Бизнес и Стратегия', [('predprinimatelstvo', 'Предпринимательство'), ('strategicheskiy_analiz', 'Стратегический анализ'), ('peregovory_i_vliyanie', 'Переговоры и влияние'), ('marketing_i_pozitsionirovanie', 'Маркетинг и позиционирование')]), ('Искусство и Культура', [('istoriya_iskusstva', 'История искусства'), ('muzyka_i_literatura', 'Музыка и литература'), ('kulturologiya', 'Культурология'), ('analiz_proizvedeniy', 'Анализ произведений')]), ('Образование и Научпоп', [('obuchayushie_texty', 'Обучающие тексты'), ('spravochniki_gaydi', 'Справочники, гайды'), ('razbor_ponyatiy', 'Разбор понятий'), ('metodiki_i_praktiki', 'Методики и практики')]), ('Литературная авторская проза', [('esse', 'Эссе'), ('literaturnye_zarisovki', 'Литературные зарисовки'), ('mini_romany', 'Мини-романы'), ('dialogi_manifesty', 'Диалоги/манифесты')]), ('Концепции и Идеи', [('teorii_i_gipotezy', 'Теории и гипотезы'), ('novye_modeli_mira', 'Новые модели мира'), ('manifesty', 'Манифесты'), ('vizualizaciya_idey', 'Визуализация идей')]), ('Саморазвитие и внутренняя система', [('disciplina', 'Дисциплина'), ('printsipy_i_cennosti', 'Принципы и ценности'), ('celepologanie', 'Целеполагание'), ('lichnaya_strategiya', 'Личная стратегия')]), ('Опасные системы и закрытые знания (Ответственность за восприятие и использование лежит на читателе)', [('manipulyacionnye_sistemy', 'Манипуляционные системы'), ('socialnaya_inzheneriya', 'Социальная инженерия'), ('sistemy_podchinenia_i_vliyania', 'Системы подчинения и влияния'), ('podryvnye_modeli_myshleniya', 'Подрывные модели мышления'), ('struktury_kontrolya', 'Структуры контроля и управление массами'), ('kognitivnye_lovushki', 'Когнитивные ловушки и архитектура убеждения')]), ('Материалы 18+ (С маркировкой NSFW. Публикация возможно при соблюдении всех правил, продукт с такой темой проходит более детальную проверку у администрации)', [('erotika_i_psihoseksualnye_modeli', 'Эротика и психосексуальные модели'), ('provokacionnaya_literatura', 'Провокационная литература'), ('psihologia_vlasti_i_dominirovaniia', 'Психология власти и доминирования'), ('intimnye_filosofskie_manifesty', 'Интимные философские манифесты'), ('telesnost_i_granicy', 'Телесность и границы восприятия')])], help_text='Категория продукта', max_length=100, null=True),
        ),
    ]
