# Generated by Django 5.1.2 on 2025-05-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_textproduct_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textproduct',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='textproduct',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='textproduct',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textproduct',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На рассмотрении'), ('approved', 'Одобрен'), ('rejected', 'Отклонён')], db_index=True, default='draft', max_length=10),
        ),
    ]
