# Generated by Django 5.1.2 on 2025-06-01 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_remove_textproduct_is_approved_textproduct_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='available_copies',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='artwork',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Черновик'),
                    ('pending', 'На модерации'),
                    ('approved', 'Одобрен'),
                    ('rejected', 'Отклонён')
                ],
                default='draft',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='artwork',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='artworkimage',
            name='censored_image',
            field=models.ImageField(blank=True, null=True, upload_to='artworks/censored/'),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='artwork',
            field=models.ForeignKey(
                to='users.artwork',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='pages'
            ),
        ),
        migrations.AlterField(
            model_name='artworkimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(
                    to='users.artwork',
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='purchases'
                )),
                ('user', models.ForeignKey(
                    to=settings.AUTH_USER_MODEL,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='purchases'
                )),
            ],
        ),
    ]
