# Generated by Django 5.1.2 on 2025-06-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_artwork_available_copies_artwork_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
