# Generated by Django 5.1.2 on 2025-06-12 20:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_artwork_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена от 0 до 10 000 000.00, с точностью до сотых', max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(Decimal('10000000.00'))]),
        ),
    ]
