# Generated by Django 5.1.2 on 2025-06-16 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_artwork_currency_artwork_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='block_reason',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='Не продавать до указанной даты', null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='nsfw',
            field=models.BooleanField(default=False, help_text='Отметьте, если содержимое может быть эротическим (NSFW)'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ban_reason',
            field=models.CharField(blank=True, help_text='Причина блокировки', max_length=200),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ban_until',
            field=models.DateTimeField(blank=True, help_text='Дата окончания бана (пусто — навсегда)', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False, help_text='Отметка для полной блокировки пользователя'),
        ),
        migrations.AddField(
            model_name='textproduct',
            name='block_reason',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='textproduct',
            name='blocked_until',
            field=models.DateTimeField(blank=True, help_text='Не продавать до указанной даты', null=True),
        ),
        migrations.AddField(
            model_name='textproduct',
            name='nsfw',
            field=models.BooleanField(default=False, help_text='Отметьте, если содержимое может быть эротическим (NSFW)'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
