# Generated by Django 5.1.2 on 2025-06-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_artwork_block_reason_artwork_blocked_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textproduct',
            name='category',
            field=models.CharField(blank=True, choices=[('Аналитика и Исследования', [('geopolitics', 'Геополитика'), ('economy_finance', 'Экономика и финансы'), ('social_processes', 'Социальные процессы'), ('scientific_reviews', 'Научные обзоры')]), ('Психология и Человеческое поведение', [('behavioral_psychology', 'Поведенческая психология'), ('dark_psychology', 'Темная психология'), ('emotional_intelligence', 'Эмоциональный интеллект'), ('self_analysis_control', 'Самоанализ и самоконтроль')]), ('Философия и Мировоззрение', [('ethics_morality', 'Этика и мораль'), ('logic_rationality', 'Логика и рациональность'), ('ontology_thinking', 'Онтология, мышление'), ('modern_philosophy', 'Современная философия')]), ('Бизнес и Стратегия', [('entrepreneurship', 'Предпринимательство'), ('strategic_analysis', 'Стратегический анализ'), ('negotiations_influence', 'Переговоры и влияние'), ('marketing_positioning', 'Маркетинг и позиционирование')]), ('Искусство и Культура', [('art_history', 'История искусства'), ('music_literature', 'Музыка и литература'), ('cultural_studies', 'Культурология'), ('work_analysis', 'Анализ произведений')]), ('Образование и Научпоп', [('educational_texts', 'Обучающие тексты'), ('guides_handbooks', 'Справочники, гайды'), ('concepts_review', 'Разбор понятий'), ('methods_practice', 'Методики и практики')]), ('Литературная авторская проза', [('essays', 'Эссе'), ('literary_sketches', 'Литературные зарисовки'), ('mini_novels', 'Мини-романы'), ('dialogues_manifestos', 'Диалоги/манифесты')]), ('Концепции и Идеи', [('theories_hypotheses', 'Теории и гипотезы'), ('new_world_models', 'Новые модели мира'), ('manifestos', 'Манифесты'), ('ideas_visualization', 'Визуализация идей')]), ('Саморазвитие и внутренняя система', [('discipline', 'Дисциплина'), ('principles_values', 'Принципы и ценности'), ('goal_setting', 'Целеполагание'), ('personal_strategy', 'Личная стратегия')]), ('Опасные системы и закрытые знания (NSFW)', [('manipulation_systems', 'Манипуляционные системы'), ('social_engineering', 'Социальная инженерия'), ('control_influence', 'Системы подчинения и влияния'), ('disruptive_thinking', 'Подрывные модели мышления'), ('mass_control_structures', 'Структуры контроля и управление массами'), ('cognitive_traps', 'Когнитивные ловушки и архитектура убеждения')]), ('Эротические материалы (NSFW)', [('erotica_psychosexual', 'Эротика и психосексуальные модели'), ('provocative_literature', 'Провокационная литература'), ('power_domination_psych', 'Психология власти и доминирования'), ('intimate_manifestos', 'Интимные философские манифесты'), ('corporeality_borders', 'Телесность и границы восприятия')])], help_text='Категория продукта', max_length=100, null=True),
        ),
    ]
