# Generated by Django 5.1.2 on 2025-06-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_textproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='currency',
            field=models.CharField(choices=[('USDT', 'Tether USD'), ('OSP', 'Ospyral Coin')], default='OSP', help_text='Выберите валюту', max_length=4),
        ),
    ]
