# Generated by Django 5.1.2 on 2025-06-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_refundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='textproductorder',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
