# Generated by Django 5.1.2 on 2025-07-09 12:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_textproductorder_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='amount',
            field=models.DecimalField(max_digits=30, decimal_places=0, default=Decimal('0')),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='order_id',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('RELEASED', 'Выполнено'), ('REFUNDED', 'Возврат')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='tx_hash',
            field=models.CharField(default='', max_length=66),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.artwork'),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='artworkorder',
            name='price',
        ),
        migrations.RemoveField(
            model_name='artworkorder',
            name='purchased_at',
        ),
        migrations.AlterUniqueTogether(
            name='artworkorder',
            unique_together={('user', 'artwork', 'order_id')},
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))])),
                ('currency', models.CharField(choices=[('USDT', 'Tether USD'), ('OSP', 'Ospyral Coin')], default='USDT', max_length=4)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Отменён')], db_index=True, default='pending', max_length=10)),
                ('tx_hash', models.CharField(blank=True, help_text='Хэш транзакции on-chain после оплаты', max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to='users.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'artwork', 'status')},
            },
        ),
    ]
