# Generated by Django 5.1.2 on 2025-07-19 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_artworkorder_unique_together_artwork_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkorder',
            name='external_order_id',
            field=models.BigIntegerField(default=0, help_text='ID заказа из смарт‑контракта', unique=True),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='artworkorder',
            unique_together={('user', 'artwork', 'external_order_id')},
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='escrow_released',
            field=models.BooleanField(default=False, help_text='Флаг, что эскроу было освобождено'),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='Когда эскроу было освобождено', null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='last_scanned_block',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='Сумма в базовой единице (wei, satoshi и т.д.)', max_digits=30),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='artwork',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.artwork'),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Время создания записи'),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Ожидание'), ('RELEASED', 'Выполнено'), ('REFUNDED', 'Возврат'), ('COMPLETED', 'Завершён')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='tx_hash',
            field=models.CharField(help_text='hash транзакции createOrder', max_length=66),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artwork_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='artworkorder',
            name='order_id',
        ),
    ]
