# Generated by Django 5.1.2 on 2025-07-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_artworkorder_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artworkorder',
            name='external_order_id',
            field=models.BigIntegerField(blank=True, help_text='ID заказа из смарт‑контракта (для OSP может быть пустым)', null=True, unique=True),
        ),
    ]
