# Generated by Django 5.1.2 on 2025-08-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customuser_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='textproduct',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
