# Generated by Django 5.1.2 on 2025-08-22 23:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_textproduct_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkorder',
            name='deposit_tx',
            field=models.CharField(blank=True, db_index=True, help_text='tx hash депозита в эскроу', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='escrow_timeout_at',
            field=models.DateTimeField(blank=True, help_text='Срок, после которого возможен таймаут (по данным контракта)', null=True),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='onchain_status',
            field=models.CharField(blank=True, db_index=True, help_text='CREATED/DEPOSITED/RELEASED/REFUNDED/TIMEOUT', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='refund_tx',
            field=models.CharField(blank=True, db_index=True, help_text='tx hash возврата покупателю', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AddField(
            model_name='artworkorder',
            name='release_tx',
            field=models.CharField(blank=True, db_index=True, help_text='tx hash релиза продавцу', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AddField(
            model_name='cryptotransaction',
            name='amount_micros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='balance_micros',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='textproductorder',
            name='deposit_tx',
            field=models.CharField(blank=True, db_index=True, help_text='tx hash депозита в эскроу', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AddField(
            model_name='textproductorder',
            name='escrow_timeout_at',
            field=models.DateTimeField(blank=True, help_text='Срок, после которого возможен таймаут (по данным контракта)', null=True),
        ),
        migrations.AddField(
            model_name='textproductorder',
            name='external_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID заказа в смарт-контракте (uint256/bytes32/строка)', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AddField(
            model_name='textproductorder',
            name='onchain_status',
            field=models.CharField(blank=True, db_index=True, help_text='CREATED/DEPOSITED/RELEASED/REFUNDED/TIMEOUT', max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='textproductorder',
            name='refund_tx',
            field=models.CharField(blank=True, db_index=True, help_text='tx hash возврата покупателю', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AddField(
            model_name='textproductorder',
            name='release_tx',
            field=models.CharField(blank=True, db_index=True, help_text='tx hash релиза продавцу', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.AlterField(
            model_name='artworkorder',
            name='external_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID заказа в смарт-контракте (uint256/bytes32/строка)', max_length=66, null=True, validators=[django.core.validators.RegexValidator('^0x[a-fA-F0-9]{64}$', 'Ожидается 0x + 64 hex-символа.')]),
        ),
        migrations.CreateModel(
            name='ChainCursor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('ethereum-sepolia', 'Ethereum Sepolia'), ('ethereum-mainnet', 'Ethereum Mainnet')], max_length=64)),
                ('contract', models.CharField(db_index=True, help_text='Адрес контракта (checksum, 0x...)', max_length=42)),
                ('last_block', models.BigIntegerField(default=0, help_text='Последний обработанный блок (включительно)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'indexes': [models.Index(fields=['network', 'contract'], name='users_chain_network_551f3f_idx')],
                'unique_together': {('network', 'contract')},
            },
        ),
    ]
