# Generated by Django 5.1.2 on 2025-08-28 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0031_backfill_micros'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(db_index=True)),
                ('amount_micros', models.BigIntegerField()),
                ('status', models.CharField(choices=[('HELD', 'Held'), ('RELEASED', 'Released'), ('REFUNDED', 'Refunded'), ('DISPUTED', 'Disputed')], db_index=True, default='HELD', max_length=16)),
                ('held_at', models.DateTimeField(auto_now_add=True)),
                ('auto_release_at', models.DateTimeField(db_index=True)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('external_order_id', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('deposit_tx', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('release_tx', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('refund_tx', models.CharField(blank=True, db_index=True, max_length=66, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('order_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrows_as_seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['order_ct', 'order_id', 'status'], name='users_escro_order_c_5520e2_idx'), models.Index(fields=['auto_release_at'], name='users_escro_auto_re_1f7fdd_idx'), models.Index(fields=['external_order_id'], name='users_escro_externa_93cf9b_idx')],
                'unique_together': {('order_ct', 'order_id')},
            },
        ),
    ]
