# Generated by Django 5.1.2 on 2025-09-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_escrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='dispute_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='dispute_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='escrow',
            name='moderator_approved_refund',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
