# Generated by Django 5.1.2 on 2025-09-09 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_escrow_dispute_created_at_escrow_dispute_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPENED', 'Открыт'), ('RESOLVED', 'Закрыт')], default='OPENED', max_length=16)),
                ('reason', models.TextField(blank=True)),
                ('evidence_url', models.URLField(blank=True)),
                ('moderator_decision', models.CharField(blank=True, max_length=32)),
                ('decision_tx', models.CharField(blank=True, max_length=80)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='users.escrow')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_disputes', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_disputes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
