# Generated by Django 5.1.2 on 2025-09-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0034_dispute'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrow',
            name='disputed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='last_chain_tx_hash',
            field=models.CharField(blank=True, db_index=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='moderator_locked',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='escrow',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='escrow',
            index=models.Index(fields=['status', 'disputed', 'moderator_locked', 'auto_release_at'], name='users_escro_status_9be18b_idx'),
        ),
    ]
