# Generated by Django 5.1.2 on 2025-09-15 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_escrow_disputed_escrow_last_chain_tx_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VIPPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('price_usd_micros', models.BigIntegerField()),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OspTopUpOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd_micros', models.BigIntegerField()),
                ('reference', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='osp_topups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VIPSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.vipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vip_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('DEBIT', 'Debit'), ('CREDIT', 'Credit')], max_length=6)),
                ('kind', models.CharField(choices=[('TOPUP_OSP_SOFT', 'Topup Osp Soft'), ('PURCHASE_VIP', 'Purchase Vip'), ('PURCHASE_PRODUCT', 'Purchase Product'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('ESCROW_REFUND', 'Escrow Refund'), ('REVERSAL', 'Reversal')], max_length=32)),
                ('currency', models.CharField(max_length=4)),
                ('amount_micros', models.BigIntegerField()),
                ('balance_after_micros', models.BigIntegerField()),
                ('reference', models.CharField(blank=True, db_index=True, max_length=128)),
                ('external_tx_hash', models.CharField(blank=True, max_length=66)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='users.cryptowallet')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'wallet', 'created_at'], name='users_ledge_user_id_2853a7_idx'), models.Index(fields=['reference'], name='users_ledge_referen_b583a6_idx'), models.Index(fields=['kind', 'created_at'], name='users_ledge_kind_b6600c_idx')],
            },
        ),
    ]
