# Generated by Django 5.1.2 on 2025-09-16 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_vipplan_osptopuporder_vipsubscription_ledgerentry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['status', 'is_active', 'available_copies'], name='users_artwo_status_1f2c4a_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['blocked_until'], name='users_artwo_blocked_c86469_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['currency', 'price'], name='users_artwo_currenc_2556a4_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['approved_at', 'id'], name='users_artwo_approve_02b077_idx'),
        ),
        migrations.AddIndex(
            model_name='artwork',
            index=models.Index(fields=['category', 'nsfw'], name='users_artwo_categor_102325_idx'),
        ),
    ]
