# Generated by Django 5.1.2 on 2025-10-05 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_artwork_users_artwo_status_1f2c4a_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vipplan',
            old_name='price_usd_micros',
            new_name='price_osp_micros',
        ),
        migrations.AddField(
            model_name='vipplan',
            name='daily_quota',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vipplan',
            name='level',
            field=models.CharField(choices=[('GOLD', 'Gold VIP'), ('STAR', 'Star VIP'), ('GALAXY', 'Galaxy VIP')], default='GOLD', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vipplan',
            name='min_interval_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vipplan',
            name='popularity_boost',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CreationQuotaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('TEXT_CREATED', 'Text Created'), ('TEXT_SUBMITTED', 'Text Submitted'), ('ART_CREATED', 'Art Created'), ('ART_SUBMITTED', 'Art Submitted'), ('REJECTED', 'Rejected')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='users_creat_user_id_831f48_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProductCooldown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('until', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('last_triggered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creation_cooldowns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'until'], name='users_userp_user_id_6ea5eb_idx')],
            },
        ),
    ]
