# Generated by Django 5.1.2 on 2025-10-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_rename_price_usd_micros_vipplan_price_osp_micros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipplan',
            name='level',
            field=models.CharField(choices=[('GOLD', 'Gold'), ('STAR', 'Star'), ('GALAXY', 'Galaxy')], default='GOLD', max_length=20),
        ),
    ]
