# Generated by Django 5.1.2 on 2025-10-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_vipplan_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_theme',
            field=models.CharField(choices=[('COLOR', 'Цвет (палитра)'), ('GOLD', 'Gold VIP'), ('STAR', 'Star VIP'), ('GALAXY', 'Galaxy VIP')], default='COLOR', max_length=12),
        ),
    ]
