# Generated by Django 5.1.2 on 2025-10-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_profile_background_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='background_theme',
        ),
    ]
