# Generated by Django 5.1.2 on 2025-10-12 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_remove_profile_background_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgerentry',
            name='kind',
            field=models.CharField(choices=[('TOPUP_OSP_SOFT', 'Topup Osp Soft'), ('PURCHASE_VIP', 'Purchase Vip'), ('PURCHASE_PRODUCT', 'Purchase Product'), ('ESCROW_HOLD', 'Escrow Hold'), ('ESCROW_RELEASE', 'Escrow Release'), ('ESCROW_REFUND', 'Escrow Refund'), ('REVERSAL', 'Reversal'), ('SALE_FEE', 'Sale Fee'), ('SALE_INCOME', 'Sale Income')], max_length=32),
        ),
    ]
