# Generated by Django 5.1.2 on 2025-10-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_ledgerentry_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptowallet',
            name='chain_id',
            field=models.IntegerField(default=56),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cryptowallet',
            name='verify_nonce',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='escrow',
            name='buyer_address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='escrow',
            name='seller_address',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
