# Generated by Django 5.1.2 on 2025-10-16 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_cryptowallet_chain_id_cryptowallet_is_external_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bg_color',
            field=models.CharField(blank=True, help_text='Цвет фона профиля/ленты (#RRGGBB)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Цвет должен быть в формате #RRGGBB', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
    ]
