# Generated by Django 5.1.2 on 2025-10-21 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_artworkrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
