# Generated by Django 5.1.2 on 2025-10-23 05:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_artwork_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('ua_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('device_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BAN', 'BAN'), ('UNBAN', 'UNBAN')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_bans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ban_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
