# Generated by Django 5.1.2 on 2025-10-23 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_vipgiftrecord'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='artwork',
            constraint=models.CheckConstraint(condition=models.Q(('available_copies__gte', 0)), name='artwork_available_copies_nonnegative'),
        ),
    ]
