# Generated by Django 5.1.2 on 2025-10-26 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_news'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cryptotransaction',
            index=models.Index(fields=['reference'], name='idx_crypto_tx_reference'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference'], name='idx_ledger_reference'),
        ),
        migrations.AddConstraint(
            model_name='cryptotransaction',
            constraint=models.UniqueConstraint(fields=('wallet', 'tx_type', 'reference'), name='uniq_crypto_tx_wallet_type_ref'),
        ),
    ]
