"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
import json
from dotenv import load_dotenv
from cryptography.fernet import Fernet


BASE_DIR = Path(__file__).resolve().parent.parent

# ── ЗАГРУЗКА .env ─────────────────────────────────────────────────
load_dotenv(BASE_DIR / '.env')

# ── СЕКРЕТЫ И РЕЖИМ ────────────────────────────────────────────────
SECRET_KEY    = os.getenv('DJANGO_SECRET_KEY')
DEBUG         = os.getenv('DJANGO_DEBUG', 'False') == 'True'
ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',')



# --- RPC / Chain ---
ETH_RPC_URL = os.getenv("SEPOLIA_RPC_URL")  # единое имя
CHAIN_ID = int(os.getenv("CHAIN_ID", "11155111"))  # Sepolia
ZERO_ADDRESS = "0x0000000000000000000000000000000000000000"

# --- Escrow contract ---
ESCROW_CONTRACT_ADDRESS = os.getenv("ESCROW_CONTRACT_ADDRESS")
# ABI можно хранить прямо в settings как dict/JSON-строку ИЛИ прочитать с диска
_ESCROW_ABI_PATH = os.getenv("ESCROW_ABI_PATH", str(BASE_DIR / "data" / "escrow_abi.json"))
try:
    with open(_ESCROW_ABI_PATH, encoding="utf-8") as f:
        ESCROW_ABI = json.load(f)
except FileNotFoundError:
    # Если хочешь хранить ABI в settings как плоскую JSON-строку, раскомментируй:
    # ESCROW_ABI = json.loads(os.getenv("ESCROW_ABI_JSON", "[]"))
    ESCROW_ABI = []

# --- Tokens ---
USDC_TOKEN_ADDRESS = os.getenv("USDC_TOKEN_ADDRESS")
OSP_CONTRACT_ADDRESS = os.getenv("OSP_CONTRACT_ADDRESS")

_USDC_ABI_PATH = os.getenv("USDC_ABI_PATH", str(BASE_DIR / "data" / "usdc_abi.json"))
try:
    with open(_USDC_ABI_PATH, encoding="utf-8") as f:
        USDC_ABI = json.load(f)
except FileNotFoundError:
    USDC_ABI = []

USDC_TOKEN_DECIMALS = int(os.getenv("USDC_TOKEN_DECIMALS", "6"))   # или будем читать динамически
OSP_TOKEN_DECIMALS  = int(os.getenv("OSP_TOKEN_DECIMALS",  "18"))



with open(BASE_DIR / "smart-contracts/artifacts/contracts/Escrow.sol/Escrow.json") as f:
    ESCROW_ABI = json.load(f)["abi"]

_ENC = os.getenv("ENCRYPTION_KEY")
if not _ENC:
    _ENC = Fernet.generate_key().decode()

ENCRYPTION_KEY = _ENC.encode() if isinstance(_ENC, str) else _ENC


# ── CELERY / REDIS ─────────────────────────────────────────────────
CELERY_BROKER_URL     = os.getenv('CELERY_BROKER_URL')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND')


CF_TURNSTILE_SITE_KEY   = os.getenv('CF_TURNSTILE_SITE_KEY', '')
CF_TURNSTILE_SECRET_KEY = os.getenv('CF_TURNSTILE_SECRET_KEY', '')

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'widget_tweaks',
    'crispy_forms',
    'crispy_bootstrap5',
    'django.contrib.humanize'
]

CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap5",)
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

MIDDLEWARE.insert(
    MIDDLEWARE.index('django.contrib.auth.middleware.AuthenticationMiddleware')+1,
    'users.middleware.CheckBanMiddleware'
)

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                "users.context_processors.unread_notifications",
            ],
            'string_if_invalid': '',
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'marketplace_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')    
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  

DEFAULT_FROM_EMAIL = 'MySite <ospyral.notify@gmail.com>'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/dashboard/'

AUTH_USER_MODEL = 'users.CustomUser'

AUTHENTICATION_BACKENDS = [
    'users.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': 'debug.log',  # Путь к файлу лога
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

WATERMARK_PATH = BASE_DIR / 'static' / 'images' / 'watermark.png'