limit_req_zone $binary_remote_addr zone=login_rate:10m rate=10r/m;

server {
    listen 80;
    server_name _;

    client_max_body_size 50M;

    location /static/ {
        alias /app/staticfiles/;
        access_log off;
        expires 30d;
    }

    location /media/ {
        alias /app/media/;
        access_log off;
        expires 30d;
    }

    location /secret-admin/ {
        allow 2.134.220.40;
        deny all;

        limit_req zone=login_rate burst=20 nodelay;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 120;
        proxy_connect_timeout 10;
        proxy_pass http://web:8000;
    }

    location = /login/ {
        limit_req zone=login_rate burst=20 nodelay;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 120;
        proxy_connect_timeout 10;
        proxy_pass http://web:8000;
    }

    location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 120;
        proxy_connect_timeout 10;
        proxy_pass http://web:8000;
    }
}
